trigger:
- master
- releases/*

pool:
  vmImage: 'vs2017-win2016'

jobs:

# Single task
- job: buildSingle
  displayName: Build single task
  condition: variables.task
  steps:
  - template: ci/build_downloadreleasetask.yml

