trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

jobs:

# Single task
- job: buildSingle
  displayName: Build single task
  condition: variables.task
  steps:
  - template: ci/build_downloadreleasetask.yml

