trigger:
- master
- releases/*

jobs:

# Single task
- job: buildSingle
  displayName: Build single task
  condition: and(variables.task), eq(variables.os, 'Windows_NT')
  steps:
  - template: ci/build-single-steps.yml

